site_name: My portfolio
site_url: http://raimon49.github.io/my-portfolio/
repo_url: https://github.com/raimon49/my-portfolio
site_description: raimon's OSS activity portfolio
site_author: raimon49@hotmail.com
pages:
  - Portfolio: index.md
  - Profile: profile.md
theme: flatly
