site_name: Information about raimon
site_url: http://raimon49.github.io/my-portfolio/
repo_url: https://github.com/raimon49/my-portfolio
edit_uri: ""
site_description: raimon's OSS activity portfolio
site_author: raimon49@hotmail.com
pages:
  - Portfolio: index.md
  - Profile: profile.md
markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
plugins:
  - mkdocs_safe_text
theme: flatly
